export enum EParentStationStatus {
  DISCOVERING = "DISCOVERING",
  CONNECTING = "CONNECTING",
  CONNECTED = "CONNECTED",
  CRY_ALERT = "CRY_ALERT",
  CONNECTION_LOST = "CONNECTION_LOST",
  DISCONNECTED = "DISCONNECTED",
  ERROR = "ERROR",
}
